# Generated by Django 5.2.13 on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_campaignparticipation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignparticipation',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='waiting', max_length=20),
        ),
    ]
