# Generated by Django 5.2.13 on 2026-04-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0002_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='required_skills',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
