# Generated by Django 5.2.13 on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0003_campaign_required_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
    ]
