# Generated by Django 5.2.13 on 2026-04-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0002_campaign_status'),
        ('ngo', '0004_campaign_urgency'),
    ]

    operations = [
    ]
